[2025-08-25T03:59:34.423+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-25T03:59:34.440+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: books_pipeline_dag.dbt_build manual__2025-08-25T03:59:29.597475+00:00 [queued]>
[2025-08-25T03:59:34.443+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: books_pipeline_dag.dbt_build manual__2025-08-25T03:59:29.597475+00:00 [queued]>
[2025-08-25T03:59:34.443+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-25T03:59:34.448+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_build> on 2025-08-25 03:59:29.597475+00:00
[2025-08-25T03:59:34.451+0000] {standard_task_runner.py:64} INFO - Started process 195 to run task
[2025-08-25T03:59:34.452+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'books_pipeline_dag', 'dbt_build', 'manual__2025-08-25T03:59:29.597475+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/books_pipeline_dag.py', '--cfg-path', '/tmp/tmp5bbdkjn7']
[2025-08-25T03:59:34.454+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask dbt_build
[2025-08-25T03:59:34.480+0000] {task_command.py:426} INFO - Running <TaskInstance: books_pipeline_dag.dbt_build manual__2025-08-25T03:59:29.597475+00:00 [running]> on host 267439edb455
[2025-08-25T03:59:34.518+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='books_pipeline_dag' AIRFLOW_CTX_TASK_ID='dbt_build' AIRFLOW_CTX_EXECUTION_DATE='2025-08-25T03:59:29.597475+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-25T03:59:29.597475+00:00'
[2025-08-25T03:59:34.519+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-25T03:59:34.524+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-25T03:59:34.524+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt deps && dbt build --profiles-dir .']
[2025-08-25T03:59:34.529+0000] {subprocess.py:86} INFO - Output:
[2025-08-25T03:59:35.999+0000] {subprocess.py:93} INFO - [0m03:59:35  Running with dbt=1.10.9
[2025-08-25T03:59:36.117+0000] {subprocess.py:93} INFO - [0m03:59:36  Warning: No packages were found in packages.yml
[2025-08-25T03:59:36.118+0000] {subprocess.py:93} INFO - [0m03:59:36  Warning: No packages were found in packages.yml
[2025-08-25T03:59:39.457+0000] {subprocess.py:93} INFO - [0m03:59:39  Running with dbt=1.10.9
[2025-08-25T03:59:39.675+0000] {subprocess.py:93} INFO - [0m03:59:39  Registered adapter: duckdb=1.9.4
[2025-08-25T03:59:39.713+0000] {subprocess.py:93} INFO - [0m03:59:39  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-08-25T03:59:40.486+0000] {subprocess.py:93} INFO - [0m03:59:40  Found 2 models, 4 data tests, 429 macros
[2025-08-25T03:59:40.488+0000] {subprocess.py:93} INFO - [0m03:59:40
[2025-08-25T03:59:40.488+0000] {subprocess.py:93} INFO - [0m03:59:40  Concurrency: 4 threads (target='dev')
[2025-08-25T03:59:40.489+0000] {subprocess.py:93} INFO - [0m03:59:40
[2025-08-25T03:59:40.558+0000] {subprocess.py:93} INFO - [0m03:59:40
[2025-08-25T03:59:40.559+0000] {subprocess.py:93} INFO - [0m03:59:40  Finished running  in 0 hours 0 minutes and 0.07 seconds (0.07s).
[2025-08-25T03:59:40.560+0000] {subprocess.py:93} INFO - [0m03:59:40  Encountered an error:
[2025-08-25T03:59:40.560+0000] {subprocess.py:93} INFO - Runtime Error
[2025-08-25T03:59:40.561+0000] {subprocess.py:93} INFO -   IO Error: Cannot open file "/opt/***/data/warehouse/books.duckdb": No such file or directory
[2025-08-25T03:59:42.666+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-25T03:59:42.669+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-25T03:59:42.692+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-25T03:59:42.703+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=books_pipeline_dag, task_id=dbt_build, run_id=manual__2025-08-25T03:59:29.597475+00:00, execution_date=20250825T035929, start_date=20250825T035934, end_date=20250825T035942
[2025-08-25T03:59:42.743+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task dbt_build (Bash command failed. The command returned a non-zero exit code 2.; 195)
[2025-08-25T03:59:42.760+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-25T03:59:42.784+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-25T03:59:42.785+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
